### ISSUE TITLE
[1.0.4] Log Spam - The rain time is being logged on every world tick

### ISSUE THREAD

**Issue by TigerWalts** [TheIcyOne/Hydrophobia#2]
This is generating about 200MB of logfile an hour.

Here's the line of code doing it:
https://github.com/TheIcyOne/Hydrophobia/blob/c108e3c5b001db102fb9640fc8beec0e1ec0ae5c/src/main/java/com/headfishindustries/hydrophobia/EventHandler.java#L33

Maybe only log it every 500 ticks or so, if needed for debugging.
```java
if (wi.getRainTime() % 500 == 0) {
    Hydrophobia.LOGGER.info(wi.getRainTime());
}
```

**Comment by harlowjg** [comment]
I concur, seeing this with 1.0.4.  as part of towncraft mod pack.

This also makes the server console unusable.

**Comment by TheIcyOne** [comment]
Oops, left a debug line in. Fix incoming, and sorry for the mess ;)

**Comment by TheIcyOne** [comment]
Update pushed to curseforge.
